### ISSUE TITLE
Selecting individual channels throws a ValueError

### ISSUE THREAD

**Issue by MeyerBender** [scverse/napari-spatialdata#282] opened 2024-08-06 11:33 UTC
Hi,

I tried to select individual channels, but keep getting a bug along the lines of `ValueError: applied function returned data with an unexpected number of dimensions.`. For 3-channel images, the bug does not occur, but it is also not possible to select channels on the right side in this case.

Minimal example:
```
import numpy as np
import spatialdata
from napari_spatialdata import Interactive

# works, but can't select any channels
image = spatialdata.models.Image2DModel.parse(
    np.random.randint(low=0, high=255, size=(3, 3000, 3000)), dims=("c", "x", "y")
)
sd_obj = spatialdata.SpatialData(images={"image": image})

# does not work
image = spatialdata.models.Image2DModel.parse(
    np.random.randint(low=0, high=255, size=(5, 3000, 3000)), dims=("c", "x", "y")
)
sd_obj = spatialdata.SpatialData(images={"image": image})

interactive = Interactive(sd_obj)
interactive.run()
```

**Comment by LucaMarconato** [comment] 2024-08-15 12:29
Hi @MeyerBender thanks for reporting, which version of `napari-spatialdata` are you using? The bug could be related to https://github.com/scverse/napari-spatialdata/pull/276/files.

**Comment by MeyerBender** [comment] 2024-08-16 13:52
Hi @LucaMarconato, this was with version `0.5.1`.

**Comment by LucaMarconato** [comment] 2024-08-16 15:20
Thanks, looks like the bug has been introduced in #276. I could reproduce the bug; I will have a look at this.

**Comment by LucaMarconato** [comment] 2024-08-19 18:15
The bug is now fixed and will make it into the next release. Meanwhile please install the latest `main` from GitHub. Thanks again for reporting!

**Closed** 2024-08-19 18:57 UTC
