### ISSUE TITLE
Use napari Points instead of napari Ellipses when SpatialData Shapes are actually circles

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/napari-spatialdata#37] opened 2023-02-08 22:03 UTC
This would improve performance 5-10x, but as explained in the linked issue we can't do it right now, because there is an issue with points size when zooming. https://github.com/scverse/napari-spatialdata/issues/35

**Comment by kevinyamauchi** [comment] 2023-02-09 07:19
@LucaMarconato , I think we really want to use points here due to the performance. It would be helpful to see a screen capture to better understand what the issue is with the point sizing.

**Comment by LucaMarconato** [comment] 2023-02-10 20:47
![points1](https://user-images.githubusercontent.com/2664412/218194198-77878f0a-944f-4a3b-a8c5-f64a8e1b002e.gif)

So I found the problem: it's not points getting smaller, but points staying the same size on screen (not getting bigger), when a certain zoom threshold is surpassed. When I zoom in beyond a certain level, everything keeps getting bigger but the points stay the same size on screen, so it seems that they get smaller and smaller.

**Comment by rahulbshrestha** [comment] 2023-06-19 21:11
@LucaMarconato can this issue be closed? We're using points instead of ellipses for spatialdata shapes that are circles right now in the main branch.

https://github.com/scverse/napari-spatialdata/blob/291ede5d85de6026b92bda64094508a24f1b86f3/src/napari_spatialdata/_interactive.py#L111-L121

**Comment by melonora** [comment] 2023-06-20 13:35
Just for reference regarding the point visual: https://github.com/napari/napari/pull/5582

**Comment by melonora** [comment] 2023-06-28 09:24
Closing this as completed as `add_points` is already on main.

**Closed by melonora** 2023-06-28 09:24 UTC
