### ISSUE TITLE
Shape layer geometry changes when saving object to SpatialData object

### ISSUE THREAD

**Issue by olivermccallion** [scverse/napari-spatialdata#237] opened 2024-04-17 17:08 UTC
Hi,

Thanks for the fantastic work. I'm running into a problem with saving annotated shapes to my SpatialData object that I was hoping you would be able to help with.

I have followed the Xenium loading tutorial here https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/technology_xenium.html to generate a SpatialData object that contains an aligned HE image and morphology_focus multimodal segmentation image. 

This gives me:
```
SpatialData object with:
├── Images
│     ├── 'he_image': MultiscaleSpatialImage[cyx] (3, 33558, 57706), (3, 16779, 28853), (3, 8389, 14426), (3, 4194, 7213), (3, 2097, 3606)
│     └── 'morphology_focus': MultiscaleSpatialImage[cyx] (5, 44236, 25670), (5, 22118, 12835), (5, 11059, 6417), (5, 5529, 3208), (5, 2764, 1604)
├── Labels
│     ├── 'cell_labels': MultiscaleSpatialImage[yx] (44236, 25670), (22118, 12835), (11059, 6417), (5529, 3208), (2764, 1604)
│     └── 'nucleus_labels': MultiscaleSpatialImage[yx] (44236, 25670), (22118, 12835), (11059, 6417), (5529, 3208), (2764, 1604)
├── Points
│     └── 'transcripts': DataFrame with shape: (3153129, 11) (3D points)
├── Shapes
│     ├── 'cell_boundaries': GeoDataFrame shape: (21922, 1) (2D shapes)
│     ├── 'cell_circles': GeoDataFrame shape: (21922, 2) (2D shapes)
│     └── 'nucleus_boundaries': GeoDataFrame shape: (21669, 1) (2D shapes)
└── Tables
      └── 'table': AnnData (21922, 477)
with coordinate systems:
▸ 'global', with elements:
        he_image (Images), morphology_focus (Images), cell_labels (Labels), nucleus_labels (Labels), transcripts (Points), cell_boundaries (Shapes), cell_circles (Shapes), nucleus_boundaries (Shapes)
```

I am then trying to add shape annotations following the tutorial here: https://spatialdata.scverse.org/en/latest/tutorials/notebooks/notebooks/examples/napari_rois.html

I am able to add a shape annotation and export it to the SpatialData object with ```Shift+E``` (green circle)

However, if I then reload the annotation from the Elements pane, the geometry of the annotation changes (white circle)

![image](https://github.com/scverse/napari-spatialdata/assets/19573710/a506dd4a-db66-4355-a80e-3f141543ba92)

Would you possibly be able to point me in the right direction for how to fix this? Sorry if this is a simple question.

Thanks!

**Comment by melonora** [comment] 2024-05-10 15:53
sorry we didn't get back to you earlier. I will try to reproduce from my side.

**Comment by melonora** [comment] 2024-05-21 09:51
Hi @olivermccallion, I tried to reproduce using an example dataset but I don't get this issue. Could you tell me whether your issue persists and if so could you give us more information regarding what versions you are using and your environment (mac, windows, linux etc)? See below what I get:
![image](https://github.com/scverse/napari-spatialdata/assets/22346363/fc47c908-7126-4956-99db-fd9e3d7d8612)

**Comment by LucaMarconato** [comment] 2024-07-10 19:39
I also confirm that I cannot reproduce the behavior. I will close the issue; please if the issue persists after installing the latest `spatialdata`, `spatialdata-io` and `napari-spatialdata` versions from `pip`, feel free to reopen this issue.

In such a case, please provide information on the operating system, Python version and library versions you are using, and a step by step guide on how to reproduce. Thank you 😊

**Closed by LucaMarconato** 2024-07-10 19:39 UTC
